#!/bin/bash
set -eux

function install() {
  local iniFile="${PHP_INI_SCAN_DIR}/${1}.ini"
  if [ -f ${iniFile} ];then
    echo "Package ${1} already installed"
    return
  fi
  case ${1} in
    'amqp')
        yum install -y librabbitmq-devel \
        && echo -e "\n" | pecl install amqp-1.9.4 \
        && echo "extension=amqp.so" > ${iniFile}
    ;;
    'apcu')
        echo -e "\n" | pecl install apcu-5.1.17 \
        && echo "extension=apcu.so" > ${iniFile} \
        && pecl install apcu_bc-1.0.5 \
        && echo "extension=apc.so" >> ${iniFile}
    ;;
    'cmark')
        curl -L -o cmake-3.15.1.tar.gz https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz \
        && tar -zxf cmake-3.15.1.tar.gz \
        && cd cmake-3.15.1 \
        && ./bootstrap \
        && gmake \
        && gmake install \
        && cd .. \
        && rm -rf cmake* \
        && curl -o cmark-0.29.0.tar.gz https://codeload.github.com/commonmark/cmark/tar.gz/0.29.0 \
        && tar -zxf cmark-0.29.0.tar.gz \
        && cd cmark-0.29.0 \
        && make \
        && make install \
        && cd .. \
        && rm -rf cmark* \
        && pecl install cmark-1.1.0 \
        && echo "extension=cmark.so" >> ${iniFile}
    ;;
    'ds')
        pecl install ds-1.2.9 \
        && echo "extension=ds.so" >> ${iniFile}
    ;;
    'event')
        yum install -y libevent-devel \
        && echo -e "\n\n\nyes\n\n\n\n\n" | pecl install event-2.5.3 \
        && echo "extension=event.so" > ${iniFile}
    ;;
    'gmagick')
        yum install -y GraphicsMagick-devel \
        && echo -e "\n" | pecl install gmagick-2.0.5RC1 \
        && echo "extension=gmagick.so" > ${iniFile}
    ;;
    'grpc')
        pecl install grpc-1.22.0 \
        && echo "extension=grpc.so" > ${iniFile}
    ;;
    'hrtime')
        pecl install hrtime-0.6.0 \
        && echo "extension=hrtime.so" > ${iniFile}
    ;;
    'igbinary')
        pecl install igbinary-3.0.1 \
        && echo "extension=igbinary.so" > ${iniFile}
    ;;
    'imagick')
        yum install -y ImageMagick-devel \
        && echo -e "\n" | pecl install imagick-3.4.4 \
        && echo "extension=imagick.so" > ${iniFile}
    ;;
    'libsodium')
        yum install -y libsodium-devel \
        && pecl install libsodium-2.0.21 \
        && echo "extension=sodium.so" > ${iniFile}
    ;;
    'lzf')
        echo -e "\n" | pecl install lzf-1.6.7 \
        && echo "extension=lzf.so" > ${iniFile}
    ;;
    'memcache')
        yum install -y re2c file \
        && curl -o pecl-memcache-4.0.4.tar.gz https://codeload.github.com/websupport-sk/pecl-memcache/tar.gz/4.0.4 \
        && tar -zxf pecl-memcache-4.0.4.tar.gz \
        && cd pecl-memcache-4.0.4 \
        && phpize \
        && ./configure \
        && make \
        && make install \
        && cd .. \
        && rm -rf pecl-memcache* \
        && echo "extension=memcache.so" > ${iniFile}
    ;;
    'memcached')
        install igbinary
        install msgpack
        yum install -y libmemcached-devel \
        && echo -e "\n\n\nyes\nyes\nyes\nyes\n\n\n" | pecl install memcached-3.1.3 \
        && echo "extension=memcached.so" > ${iniFile}
    ;;
    'mongo')
        install mongodb
        echo "Please see the library [https://github.com/mongodb/mongo-php-library]"
    ;;
    'mongodb')
        pecl install mongodb-1.5.5 \
        && echo "extension=mongodb.so" > ${iniFile}
    ;;
    'msgpack')
        pecl install msgpack-2.0.3 \
        && echo "extension=msgpack.so" > ${iniFile}
    ;;
    'oauth')
        pecl install oauth-2.0.3 \
        && echo "extension=oauth.so" > ${iniFile}
    ;;
    'rar')
        pecl install rar-4.0.0 \
        && echo "extension=rar.so" > ${iniFile}
    ;;
    'redis')
        install igbinary
        install lzf
        echo -e "yes\nyes\n" | pecl install redis-5.0.2 \
        && echo "extension=redis.so" > ${iniFile}
    ;;
    'solr')
        echo -e "\n\n\n" | pecl install solr-2.5.0 \
        && echo "extension=solr.so" > ${iniFile}
    ;;
    'ssh2')
        yum install -y libssh2-devel \
        && echo -e "\n" | pecl install ssh2-1.1.2 \
        && echo "extension=ssh2.so" > ${iniFile}
    ;;
    'stomp')
        ln -s /usr/lib64/libssl.so /usr/lib/libssl.so \
        && echo -e "\n" | pecl install stomp-2.0.2 \
        && echo "extension=stomp.so" > ${iniFile}
    ;;
    'svm')
        yum install -y libsvm-devel \
        && pecl install svm-0.2.3 \
        && echo "extension=svm.so" > ${iniFile}
    ;;
    'swoole')
        echo -e "yes\nyes\nyes\nyes\n" | pecl install swoole-4.4.3 \
        && echo "extension=swoole.so" > ${iniFile}
    ;;
    'sync')
        pecl install sync-1.1.1 \
        && echo "extension=sync.so" > ${iniFile}
    ;;
    'timezonedb')
        pecl install timezonedb \
        && echo "extension=timezonedb.so" > ${iniFile}
    ;;
    'varnish')
        yum install -y varnish-libs-devel \
        && pecl install varnish-1.2.4 \
        && echo "extension=varnish.so" > ${iniFile}
    ;;
    'xlswriter')
        pecl install xlswriter-1.2.6 \
        && echo "extension=xlswriter.so" > ${iniFile}
    ;;
    'yaf')
        pecl install yaf-3.0.8 \
        && echo "extension=yaf.so" > ${iniFile}
    ;;
    'yaml')
        yum install -y libyaml-devel \
        && echo -e "\n" | pecl install yaml-2.0.4 \
        && echo "extension=yaml.so" > ${iniFile}
    ;;
    'yar')
        install msgpack
        echo -e "yes\n" | pecl install yar-2.0.5 \
        && echo "extension=yar.so" > ${iniFile}
    ;;
    'opcache')
        echo "zend_extension=/usr/local/lib/php/extensions/$(ls /usr/local/lib/php/extensions)/opcache.so" > ${iniFile}
    ;;
    'zookeeper')
        workDir=$(pwd)
        curl -O http://mirror-hk.koddos.net/apache/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz \
        && tar -zxf zookeeper-3.4.14.tar.gz \
        && cd zookeeper-3.4.14/zookeeper-client/zookeeper-client-c \
        && ./configure \
        && make \
        && make install \
        && cd ${workDir} \
        && rm -rf zookeeper* \
        && pecl install zookeeper-0.7.1 \
        && echo "extension=zookeeper.so" > ${iniFile}
    ;;
    *)
        echo "No package ${1} available"
    ;;
  esac
}

for var in "$@"
do
  install $var
done

yum clean all
pecl clear-cache
